### ISSUE TITLE
reduce the size of each information box; align left/right appropriately

### ISSUE THREAD

**Issue by chrzrdx** [VenkatPantham/edyst-s19-pokemon-battle-scene#1]

**Comment by chrzrdx** [comment]
add a small oval below the pokemon, to make it appear as if the pokemon is standing on top of that oval patch of grass/etc

Don't change the background image, try to actually make an oval patch of land here

**Comment by chrzrdx** [comment]
Increase size of pokemon, make the background container smaller and centered on the page (dont keep the background image full page width

**Comment by VenkatPantham** [comment]
Increased the sizes of the pokemons and made background small and added green patches
